FROM python:3.9-slim as builder

WORKDIR /app

COPY app.py /app
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /app /app

ENV GREETING="Hello, World!"
EXPOSE 8000

ENTRYPOINT ["python"]
CMD ["app.py"]
